### ISSUE TITLE
error aT composer install

### ISSUE THREAD

**Issue by impactfactory** [wintercms/wn-seo-plugin#1]
After php artisan plugin:install winter.seo on Winter 1.2, Terminal says:

"Downloading plugin: 

In UpdateManager.php line 947:
                                
File from server is corrupt.  "

Thanx!

**Comment by bennothommo** [comment]
@impactfactory that is not installing through Composer.

You should instead run `composer require winter/wn-seo-plugin` and then run `php artisan winter:up` to run the migrations.
