### ISSUE TITLE
Call to undefined YAML file

### ISSUE THREAD

**Issue by khutachan** [wintercms/wn-seo-plugin#11]
In the extendBackendForms() of Plugin.php, it parses a YAML file with path is  `/winter/models/seodata/fields.yaml`, that file is clearly not exist.

I have found that the error was caused by this line:
```php
$seoForm = Yaml::parseFile(plugins_path('winter/seo/models/seodata/fields.yaml')); 
```

All the YAML files that I can see in `seodata` folder is `fields.halcyon.yaml`, `fields.link.yaml`, `fields.meta.yaml`.

**Comment by LukeTowers** [comment]
This was fixed in https://github.com/wintercms/wn-seo-plugin/commit/dafc9e35a0fbd5cd1eafa014aa3aa0a022347999, I'll tag a new version.

**Comment by LukeTowers** [comment]
Actually fixed by https://github.com/wintercms/wn-seo-plugin/commit/6dfb303f1c9c29e01b27c37ad46487856a85c5cd
