### ISSUE TITLE
Undefined array key "fields" on line 179 of Plugin.php

### ISSUE THREAD

**Issue by khutachan** [wintercms/wn-seo-plugin#12]
I think we have a new issue in `Plugin.php` on line 179.

It says that `fields` key is undefined in this line of code:
```php
$widget->{$location}['fields'] = array_merge($widget->{$location}['fields'], $fields);
```

I didn't do anything except declaring my model class which is `\Cms\Models\ThemeData::class` in `seoableModels` array key of `config.php`.

**Comment by LukeTowers** [comment]
@khutachan try https://github.com/wintercms/wn-seo-plugin/pull/13 and let me know if that fixes the issue

**Comment by khutachan** [comment]
@LukeTowers I'm seeing the meta form fields, thanks for your support.
