### ISSUE TITLE
Conditionnal routing

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-seo-plugin#2]
By default the plugin adds the following routes to the site: 
 - `/humans.txt`
 - `/robots.txt`
 - `/security.txt`
 - `/.well-known/security.txt`

My problem is that in the `robots.txt` file the `Sitemap` properties must contain the domain name.
https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
> The sitemap URL must be a fully-qualified URL

To solve this problem I have created a dedicated page in this form: 
```twig
title = "Robots file"
url = "/robots.txt"
is_hidden = 0
==
<?php
    function onEnd()
    {
        /**
         * Change the content type to text/plain
         */
        $this->controller->setResponseHeader('Content-Type', 'text/plain');
    }
?>
==
# Begin robots.txt file
#
# Exclude Files From All Robots:
User-agent: *
Disallow: /bootstrap/
Disallow: /config/
Disallow: /vendor/

# Sitemaps
Sitemap: {{ '/' | app }}sitemap.xml

# End robots.txt file
```
This way, there is no need to change the domain in the text file at the site root.  
The routes defined in this plugin take priority on that page of the website.

So I ask the question if it is possible to declare these routes **only** if they are enabled through the plugin settings?

**Comment by LukeTowers** [comment]
@damsfx do you just use the Sitemap plugin for managing your sitemaps?

**Comment by LukeTowers** [comment]
A couple options come to mind immediately, I'm sure there's more:
- We could support twig parsing of the .txt file settings
- We could automatically generate a generically useful robots.txt when none is present in the settings that would solve the use case of most people and automatically detect the sitemap plugin's configuration

**Comment by damsfx** [comment]
> @damsfx do you just use the Sitemap plugin for managing your sitemaps?

Of course!  
It is always the best.  😉

**Comment by damsfx** [comment]
>     * We could support twig parsing of the .txt file settings
> 
>     * We could automatically generate a generically useful robots.txt when none is present in the settings that would solve the use case of most people and automatically detect the sitemap plugin's configuration

Great ideas.  

I'm sure this plugin can become a must-have in the Winter SEO optimization field.

**Comment by LukeTowers** [comment]
@damsfx we now support per-env configuration of those three files, let me know if that works for your use case: https://github.com/wintercms/wn-seo-plugin/blob/main/config/config.php#L3-L11

**Comment by LukeTowers** [comment]
@damsfx we now support twig parsing of those three files: https://github.com/wintercms/wn-seo-plugin/commit/b3395579b23145a392ccb9a3f899cbab8a25df19
