### ISSUE TITLE
Problem install wn-seo-plugin using composer

### ISSUE THREAD

**Issue by Melki-Sap** [wintercms/wn-seo-plugin#7]
Hi Luke and everyone,

I use winter CMS for some of my mini project, and i grateful for it. And i had a problem when i install wn-seo-plugin using composer, my status is using nginx and php7.2 and install using **composer require winter/wn-seo-plugin**.

`In routes.php line 16:

  syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'

Script @php artisan package:discover handling the post-update-cmd event returned with error code 1`

Please let me know if there's an error on my side or there's any update on the package.

**Comment by LukeTowers** [comment]
Arrow functions were only introduced in PHP 7.4, you're going to need to upgrade your PHP version. I highly recommend you upgrade to PHP 8.1 or 8.2 and to Winter v1.2.3+, see https://github.com/wintercms/meta/blob/master/l9-upgrade-notes.md

**Comment by Melki-Sap** [comment]
Hi Luke,

Sorry for late Respond, will do it now.  And Thank you.
